^!1:: send, {Ctrl down}{LAlt down}1{Ctrl up}{LAlt up}
^!2:: send, {Ctrl down}{LAlt down}2{Ctrl up}{LAlt up}
^!3:: send, {Ctrl down}{LAlt down}3{Ctrl up}{LAlt up}
^!4:: send, {Ctrl down}{LAlt down}4{Ctrl up}{LAlt up}
^!5:: send, {Ctrl down}{LAlt down}5{Ctrl up}{LAlt up}
^!6:: send, {Ctrl down}{LAlt down}6{Ctrl up}{LAlt up}
^!7:: send, {Ctrl down}{LAlt down}7{Ctrl up}{LAlt up}
^!8:: send, {Ctrl down}{LAlt down}8{Ctrl up}{LAlt up}
^!9:: send, {Ctrl down}{LAlt down}9{Ctrl up}{LAlt up}
^!0:: send, {Ctrl down}{LAlt down}0{Ctrl up}{LAlt up}
^!-:: send, {Ctrl down}{LAlt down}-{Ctrl up}{LAlt up}
^!=:: send, {Ctrl down}{LAlt down}={Ctrl up}{LAlt up}
^!a:: send, {Ctrl down}{LAlt down}a{Ctrl up}{LAlt up}
^!b:: send, {Ctrl down}{LAlt down}b{Ctrl up}{LAlt up}
^!c:: send, {Ctrl down}{LAlt down}c{Ctrl up}{LAlt up}
^!d:: send, {Ctrl down}{LAlt down}d{Ctrl up}{LAlt up}
^!e:: send, {Ctrl down}{LAlt down}e{Ctrl up}{LAlt up}
^!f:: send, {Ctrl down}{LAlt down}f{Ctrl up}{LAlt up}
^!g:: send, {Ctrl down}{LAlt down}g{Ctrl up}{LAlt up}
^!h:: send, {Ctrl down}{LAlt down}h{Ctrl up}{LAlt up}
^!i:: send, {Ctrl down}{LAlt down}i{Ctrl up}{LAlt up}
^!j:: send, {Ctrl down}{LAlt down}j{Ctrl up}{LAlt up}
^!k:: send, {Ctrl down}{LAlt down}k{Ctrl up}{LAlt up}
^!l:: send, {Ctrl down}{LAlt down}l{Ctrl up}{LAlt up}
^!m:: send, {Ctrl down}{LAlt down}m{Ctrl up}{LAlt up}
^!n:: send, {Ctrl down}{LAlt down}n{Ctrl up}{LAlt up}
^!o:: send, {Ctrl down}{LAlt down}o{Ctrl up}{LAlt up}
^!p:: send, {Ctrl down}{LAlt down}p{Ctrl up}{LAlt up}
^!q:: send, {Ctrl down}{LAlt down}q{Ctrl up}{LAlt up}
^!r:: send, {Ctrl down}{LAlt down}r{Ctrl up}{LAlt up}
^!s:: send, {Ctrl down}{LAlt down}s{Ctrl up}{LAlt up}
^!t:: send, {Ctrl down}{LAlt down}t{Ctrl up}{LAlt up}
^!u:: send, {Ctrl down}{LAlt down}u{Ctrl up}{LAlt up}
^!v:: send, {Ctrl down}{LAlt down}v{Ctrl up}{LAlt up}
^!w:: send, {Ctrl down}{LAlt down}w{Ctrl up}{LAlt up}
^!x:: send, {Ctrl down}{LAlt down}x{Ctrl up}{LAlt up}
^!y:: send, {Ctrl down}{LAlt down}y{Ctrl up}{LAlt up}
^!z:: send, {Ctrl down}{LAlt down}z{Ctrl up}{LAlt up}
^!,:: send, {Ctrl down}{LAlt down},{Ctrl up}{LAlt up}
^!.:: send, {Ctrl down}{LAlt down}.{Ctrl up}{LAlt up}
^!/:: send, {Ctrl down}{LAlt down}/{Ctrl up}{LAlt up}
^!\:: send, {Ctrl down}{LAlt down}\{Ctrl up}{LAlt up}
^![:: send, {Ctrl down}{LAlt down}[{Ctrl up}{LAlt up}
^!]:: send, {Ctrl down}{LAlt down}]{Ctrl up}{LAlt up}
^!;:: send, {Ctrl down}{LAlt down};{Ctrl up}{LAlt up}
^!`:: send, {Ctrl down}{LAlt down}``{Ctrl up}{LAlt up}
